version: '2.1'
services:
  config-node:
    container_name: config-node
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      config-mongo:
        condition: service_healthy
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_METRICS_HOST:$GLS_METRICS_PORT:$GLS_METRICS_PORT
    env_file:
      - .env

  config-mongo:
    container_name: config-mongo
    image: mongo
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - config_mongodb_vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier

networks:
  services-tier:

volumes:
  config_mongodb_vol:
